version: '3.3'

services:
    nginx_base:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-}
                CONTAINER_NAME: nginx_base
                FROM_BASE: ${DOCKER_REGISTRY:-}${OS:-}supervisord:${BASE_TAG:-latest}
                NGINX_DEBUG: 1
            cache_from:
                - ${DOCKER_REGISTRY:-}${OS:-}alpine:3.8
                - ${DOCKER_REGISTRY:-}${OS:-}base_container:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-}${OS:-}supervisord:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: nginx_base
        container_name: nginx_base
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
#            PWD_PROTECTED: 'true'
            SUPERVISORD_PASS: $CFG_PASS
            SUPERVISORD_USER: $CFG_USER
#            USER_ID: $CFG_USER
#            USER_PASS: $CFG_PASS
        hostname: nginx_base
        image: ${DOCKER_REGISTRY:-}${OS:-}nginx_base/1.15.1:${CONTAINER_TAG:-latest}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
           - 80:80
           - 9001:9001
# only use when building a 'service container'
#        restart: unless-stopped
