version: '3.3'

services:
    nginx_base:
        build:
            args:
                CBF_VERSION: "${CBF_VERSION:-}"
                CONTAINER_NAME: nginx_base
                CONTAINER_VERSION: ${CONTAINER_VERSION:-3.0.0}
                FROM_BASE: supervisord:${CONTAINER_TAG:-latest}
            cache_from:
                - alpine:3.8
                - base_container:${CONTAINER_TAG:-latest}
                - supervisord:${CONTAINER_TAG:-latest}
            context: .
            dockerfile: Dockerfile
        container_name: nginx_base
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            SUPERVISORD_PASS: $CFG_PASS
            SUPERVISORD_USER: $CFG_USER 
        hostname: nginx_base
        image: nginx_base:${CONTAINER_TAG:-latest}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
           - 80:80
           - 9001:9001
# only use when building a 'service container'
#        restart: unless-stopped
